# Generated by Django 4.1.7 on 2023-05-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(blank=True, max_length=20)),
                ('test2', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
